# https://docs.github.com/en/actions
name: Java CI (repo-build-test)

on: push

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

  setup-jdk:
    name: Setup Java JDK
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven #cache dependencies to speed up the workflow run

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build with Maven
        run: mvn clean install

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: UT
        run: mvn test

